# NCS Workflow 4: Application as the manifest repo
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_adding_code.html
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect/
  projects:
    - name: sdk-nrf
      path: nrf
      revision: main
      remote: nrfconnect
      import: true

  self:
    path: modules/lib/onomondo-softsim
 
