# Testing new method
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: softsim
      url-base: https://github.com/onomondo
  projects:
    - name: nrf
      remote: ncs
      revision: 2.6.1
      import: true
    - name: softsim
      remote: softsim
      repo-path: nrf-softsim
      revision: master
      path: modules/lib/onomondo-softsim
