manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect/
  projects:
    - name: sdk-nrf
      path: nrf
      revision: v3.1.1
      remote: nrfconnect
      import: true
  self:
    path: modules/lib/onomondo-softsim
