# NCS Workflow 4: Application as the manifest repo
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_adding_code.html
manifest:
  projects:
    - name: nrf
      revision: v2.2-branch-softsim
      url: git@github.com:NordicSemiconductor/sdk-nrf-softsim.git
      import: true

  self:
    path: modules/lib/onomondo-softsim
 
