name: Check Codebase Formatting

on: pull_request

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          FILES=$(find lib samples -name "*.c" -o -name "*.h" | grep -E "(lib/|samples/softsim_(external|static)_profile/)" | grep -v "lib/include/")
          clang-format --dry-run -Werror $FILES
