name: Lint Commit Messages

on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Linting commit messages
        uses: wagoid/commitlint-github-action@v5

