name: Run release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}

  # Add build artifacts to the new GitHub release
  release-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [build-in-zyphyr-ci-container, release-please]

    strategy:
      matrix:
        board: [nrf9160dk_nrf9160_ns, nrf9161dk_nrf9161_ns, nrf9151dk_nrf9151_ns]

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: softsim_external_profile_${{ matrix.board }}
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} softsim_external_profile_${{ matrix.board }}.zip
