name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          target-branch: master
